# Generated by Django 4.1.7 on 2023-03-16 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomSize', models.IntegerField(max_length=4)),
                ('noofWindows', models.IntegerField(max_length=3)),
                ('isMetro', models.BooleanField(default=False)),
            ],
        ),
    ]
