# Generated by Django 4.1.7 on 2023-03-16 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBCONN', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Villa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noOfRooms', models.IntegerField(max_length=5)),
                ('carpetArea', models.IntegerField(max_length=150)),
            ],
        ),
    ]
