# Generated by Django 4.1.7 on 2023-03-16 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBCONN', '0002_villa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employeedetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empname', models.CharField(max_length=20)),
                ('emp_age', models.IntegerField(max_length=2)),
                ('emp_id', models.CharField(max_length=8)),
                ('emp_department', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='villa',
            name='isMetro',
            field=models.BooleanField(default=False),
        ),
    ]
